/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticationImport } from './routes/_authentication'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticationVerifyOtpImport } from './routes/_authentication/verify-otp'
import { Route as AuthenticationSignUpImport } from './routes/_authentication/sign-up'
import { Route as AuthenticationResetPasswordImport } from './routes/_authentication/reset-password'
import { Route as AuthenticationLogInImport } from './routes/_authentication/log-in'
import { Route as AuthenticationForgotPasswordImport } from './routes/_authentication/forgot-password'
import { Route as AuthenticatedReportImport } from './routes/_authenticated/report'
import { Route as AuthenticatedProgressImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedFocusTimerImport } from './routes/_authenticated/focus-timer'
import { Route as AuthenticatedAnalyticsImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/_profile'
import { Route as AuthenticatedTaskManagementIndexImport } from './routes/_authenticated/task-management/index'
import { Route as AuthenticatedTaskManagementListViewImport } from './routes/_authenticated/task-management/list-view'
import { Route as AuthenticatedTaskManagementCalendarViewImport } from './routes/_authenticated/task-management/calendar-view'
import { Route as AuthenticatedProfileProfileIndexImport } from './routes/_authenticated/_profile/profile/index'
import { Route as AuthenticatedProfileProfileChangePasswordImport } from './routes/_authenticated/_profile/profile/change-password'

// Create/Update Routes

const AuthenticationRoute = AuthenticationImport.update({
  id: '/_authentication',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticationVerifyOtpRoute = AuthenticationVerifyOtpImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthenticationRoute,
} as any)

const AuthenticationSignUpRoute = AuthenticationSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthenticationRoute,
} as any)

const AuthenticationResetPasswordRoute =
  AuthenticationResetPasswordImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => AuthenticationRoute,
  } as any)

const AuthenticationLogInRoute = AuthenticationLogInImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => AuthenticationRoute,
} as any)

const AuthenticationForgotPasswordRoute =
  AuthenticationForgotPasswordImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => AuthenticationRoute,
  } as any)

const AuthenticatedReportRoute = AuthenticatedReportImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProgressRoute = AuthenticatedProgressImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedFocusTimerRoute = AuthenticatedFocusTimerImport.update({
  id: '/focus-timer',
  path: '/focus-timer',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: '/_profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedTaskManagementIndexRoute =
  AuthenticatedTaskManagementIndexImport.update({
    id: '/task-management/',
    path: '/task-management/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTaskManagementListViewRoute =
  AuthenticatedTaskManagementListViewImport.update({
    id: '/task-management/list-view',
    path: '/task-management/list-view',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTaskManagementCalendarViewRoute =
  AuthenticatedTaskManagementCalendarViewImport.update({
    id: '/task-management/calendar-view',
    path: '/task-management/calendar-view',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedProfileProfileIndexRoute =
  AuthenticatedProfileProfileIndexImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

const AuthenticatedProfileProfileChangePasswordRoute =
  AuthenticatedProfileProfileChangePasswordImport.update({
    id: '/profile/change-password',
    path: '/profile/change-password',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authentication': {
      id: '/_authentication'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticationImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_profile': {
      id: '/_authenticated/_profile'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/focus-timer': {
      id: '/_authenticated/focus-timer'
      path: '/focus-timer'
      fullPath: '/focus-timer'
      preLoaderRoute: typeof AuthenticatedFocusTimerImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authentication/forgot-password': {
      id: '/_authentication/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthenticationForgotPasswordImport
      parentRoute: typeof AuthenticationImport
    }
    '/_authentication/log-in': {
      id: '/_authentication/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof AuthenticationLogInImport
      parentRoute: typeof AuthenticationImport
    }
    '/_authentication/reset-password': {
      id: '/_authentication/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthenticationResetPasswordImport
      parentRoute: typeof AuthenticationImport
    }
    '/_authentication/sign-up': {
      id: '/_authentication/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthenticationSignUpImport
      parentRoute: typeof AuthenticationImport
    }
    '/_authentication/verify-otp': {
      id: '/_authentication/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthenticationVerifyOtpImport
      parentRoute: typeof AuthenticationImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/task-management/calendar-view': {
      id: '/_authenticated/task-management/calendar-view'
      path: '/task-management/calendar-view'
      fullPath: '/task-management/calendar-view'
      preLoaderRoute: typeof AuthenticatedTaskManagementCalendarViewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/task-management/list-view': {
      id: '/_authenticated/task-management/list-view'
      path: '/task-management/list-view'
      fullPath: '/task-management/list-view'
      preLoaderRoute: typeof AuthenticatedTaskManagementListViewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/task-management/': {
      id: '/_authenticated/task-management/'
      path: '/task-management'
      fullPath: '/task-management'
      preLoaderRoute: typeof AuthenticatedTaskManagementIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_profile/profile/change-password': {
      id: '/_authenticated/_profile/profile/change-password'
      path: '/profile/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof AuthenticatedProfileProfileChangePasswordImport
      parentRoute: typeof AuthenticatedProfileImport
    }
    '/_authenticated/_profile/profile/': {
      id: '/_authenticated/_profile/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileProfileIndexImport
      parentRoute: typeof AuthenticatedProfileImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileProfileChangePasswordRoute: typeof AuthenticatedProfileProfileChangePasswordRoute
  AuthenticatedProfileProfileIndexRoute: typeof AuthenticatedProfileProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileProfileChangePasswordRoute:
    AuthenticatedProfileProfileChangePasswordRoute,
  AuthenticatedProfileProfileIndexRoute: AuthenticatedProfileProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedFocusTimerRoute: typeof AuthenticatedFocusTimerRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTaskManagementCalendarViewRoute: typeof AuthenticatedTaskManagementCalendarViewRoute
  AuthenticatedTaskManagementListViewRoute: typeof AuthenticatedTaskManagementListViewRoute
  AuthenticatedTaskManagementIndexRoute: typeof AuthenticatedTaskManagementIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedFocusTimerRoute: AuthenticatedFocusTimerRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTaskManagementCalendarViewRoute:
    AuthenticatedTaskManagementCalendarViewRoute,
  AuthenticatedTaskManagementListViewRoute:
    AuthenticatedTaskManagementListViewRoute,
  AuthenticatedTaskManagementIndexRoute: AuthenticatedTaskManagementIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthenticationRouteChildren {
  AuthenticationForgotPasswordRoute: typeof AuthenticationForgotPasswordRoute
  AuthenticationLogInRoute: typeof AuthenticationLogInRoute
  AuthenticationResetPasswordRoute: typeof AuthenticationResetPasswordRoute
  AuthenticationSignUpRoute: typeof AuthenticationSignUpRoute
  AuthenticationVerifyOtpRoute: typeof AuthenticationVerifyOtpRoute
}

const AuthenticationRouteChildren: AuthenticationRouteChildren = {
  AuthenticationForgotPasswordRoute: AuthenticationForgotPasswordRoute,
  AuthenticationLogInRoute: AuthenticationLogInRoute,
  AuthenticationResetPasswordRoute: AuthenticationResetPasswordRoute,
  AuthenticationSignUpRoute: AuthenticationSignUpRoute,
  AuthenticationVerifyOtpRoute: AuthenticationVerifyOtpRoute,
}

const AuthenticationRouteWithChildren = AuthenticationRoute._addFileChildren(
  AuthenticationRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedProfileRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/focus-timer': typeof AuthenticatedFocusTimerRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/report': typeof AuthenticatedReportRoute
  '/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/log-in': typeof AuthenticationLogInRoute
  '/reset-password': typeof AuthenticationResetPasswordRoute
  '/sign-up': typeof AuthenticationSignUpRoute
  '/verify-otp': typeof AuthenticationVerifyOtpRoute
  '/': typeof AuthenticatedIndexRoute
  '/task-management/calendar-view': typeof AuthenticatedTaskManagementCalendarViewRoute
  '/task-management/list-view': typeof AuthenticatedTaskManagementListViewRoute
  '/task-management': typeof AuthenticatedTaskManagementIndexRoute
  '/profile/change-password': typeof AuthenticatedProfileProfileChangePasswordRoute
  '/profile': typeof AuthenticatedProfileProfileIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedProfileRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/focus-timer': typeof AuthenticatedFocusTimerRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/report': typeof AuthenticatedReportRoute
  '/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/log-in': typeof AuthenticationLogInRoute
  '/reset-password': typeof AuthenticationResetPasswordRoute
  '/sign-up': typeof AuthenticationSignUpRoute
  '/verify-otp': typeof AuthenticationVerifyOtpRoute
  '/': typeof AuthenticatedIndexRoute
  '/task-management/calendar-view': typeof AuthenticatedTaskManagementCalendarViewRoute
  '/task-management/list-view': typeof AuthenticatedTaskManagementListViewRoute
  '/task-management': typeof AuthenticatedTaskManagementIndexRoute
  '/profile/change-password': typeof AuthenticatedProfileProfileChangePasswordRoute
  '/profile': typeof AuthenticatedProfileProfileIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authentication': typeof AuthenticationRouteWithChildren
  '/_authenticated/_profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/focus-timer': typeof AuthenticatedFocusTimerRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authentication/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/_authentication/log-in': typeof AuthenticationLogInRoute
  '/_authentication/reset-password': typeof AuthenticationResetPasswordRoute
  '/_authentication/sign-up': typeof AuthenticationSignUpRoute
  '/_authentication/verify-otp': typeof AuthenticationVerifyOtpRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/task-management/calendar-view': typeof AuthenticatedTaskManagementCalendarViewRoute
  '/_authenticated/task-management/list-view': typeof AuthenticatedTaskManagementListViewRoute
  '/_authenticated/task-management/': typeof AuthenticatedTaskManagementIndexRoute
  '/_authenticated/_profile/profile/change-password': typeof AuthenticatedProfileProfileChangePasswordRoute
  '/_authenticated/_profile/profile/': typeof AuthenticatedProfileProfileIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/analytics'
    | '/focus-timer'
    | '/progress'
    | '/report'
    | '/forgot-password'
    | '/log-in'
    | '/reset-password'
    | '/sign-up'
    | '/verify-otp'
    | '/'
    | '/task-management/calendar-view'
    | '/task-management/list-view'
    | '/task-management'
    | '/profile/change-password'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/analytics'
    | '/focus-timer'
    | '/progress'
    | '/report'
    | '/forgot-password'
    | '/log-in'
    | '/reset-password'
    | '/sign-up'
    | '/verify-otp'
    | '/'
    | '/task-management/calendar-view'
    | '/task-management/list-view'
    | '/task-management'
    | '/profile/change-password'
    | '/profile'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authentication'
    | '/_authenticated/_profile'
    | '/_authenticated/analytics'
    | '/_authenticated/focus-timer'
    | '/_authenticated/progress'
    | '/_authenticated/report'
    | '/_authentication/forgot-password'
    | '/_authentication/log-in'
    | '/_authentication/reset-password'
    | '/_authentication/sign-up'
    | '/_authentication/verify-otp'
    | '/_authenticated/'
    | '/_authenticated/task-management/calendar-view'
    | '/_authenticated/task-management/list-view'
    | '/_authenticated/task-management/'
    | '/_authenticated/_profile/profile/change-password'
    | '/_authenticated/_profile/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthenticationRoute: typeof AuthenticationRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthenticationRoute: AuthenticationRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_authentication"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_profile",
        "/_authenticated/analytics",
        "/_authenticated/focus-timer",
        "/_authenticated/progress",
        "/_authenticated/report",
        "/_authenticated/",
        "/_authenticated/task-management/calendar-view",
        "/_authenticated/task-management/list-view",
        "/_authenticated/task-management/"
      ]
    },
    "/_authentication": {
      "filePath": "_authentication.tsx",
      "children": [
        "/_authentication/forgot-password",
        "/_authentication/log-in",
        "/_authentication/reset-password",
        "/_authentication/sign-up",
        "/_authentication/verify-otp"
      ]
    },
    "/_authenticated/_profile": {
      "filePath": "_authenticated/_profile.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_profile/profile/change-password",
        "/_authenticated/_profile/profile/"
      ]
    },
    "/_authenticated/analytics": {
      "filePath": "_authenticated/analytics.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/focus-timer": {
      "filePath": "_authenticated/focus-timer.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/progress": {
      "filePath": "_authenticated/progress.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/report": {
      "filePath": "_authenticated/report.tsx",
      "parent": "/_authenticated"
    },
    "/_authentication/forgot-password": {
      "filePath": "_authentication/forgot-password.tsx",
      "parent": "/_authentication"
    },
    "/_authentication/log-in": {
      "filePath": "_authentication/log-in.tsx",
      "parent": "/_authentication"
    },
    "/_authentication/reset-password": {
      "filePath": "_authentication/reset-password.tsx",
      "parent": "/_authentication"
    },
    "/_authentication/sign-up": {
      "filePath": "_authentication/sign-up.tsx",
      "parent": "/_authentication"
    },
    "/_authentication/verify-otp": {
      "filePath": "_authentication/verify-otp.tsx",
      "parent": "/_authentication"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/task-management/calendar-view": {
      "filePath": "_authenticated/task-management/calendar-view.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/task-management/list-view": {
      "filePath": "_authenticated/task-management/list-view.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/task-management/": {
      "filePath": "_authenticated/task-management/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_profile/profile/change-password": {
      "filePath": "_authenticated/_profile/profile/change-password.tsx",
      "parent": "/_authenticated/_profile"
    },
    "/_authenticated/_profile/profile/": {
      "filePath": "_authenticated/_profile/profile/index.tsx",
      "parent": "/_authenticated/_profile"
    }
  }
}
ROUTE_MANIFEST_END */
